version: "3.9"
services:
  game_master:
    image: nehcy/game_master
    container_name: GameMaster
    build: .
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - OPENAI_KEY=${OPENAI_KEY}
      - OPENAI_PROXY=${OPENAI_PROXY}
      - OPENAI_TIMER=${OPENAI_TIMER}
      - SD_URL=${SD_URL}
    command: python main.py
    init: true
    restart: always
    stdin_open: true    
    network_mode: bridge
    tty: true
